name: init

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */2 * * *" 

jobs:
  build:
    runs-on: windows-latest

    env:
      FB_TOKEN: ${{ secrets.FB_TOKEN }}
      GIT_PAT: ${{ secrets.GIT_PAT }}
      REPO_OWNER: ${{ github.repository_owner }}

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.9
        architecture: x64  

    - name: Instalar Dependências
      run: |
        python -m pip install -r src/requirements.txt

    - name: Executar script Python
      run: python src/main.py

    - name: Update arquivos
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "updated"
        repository: .
        file_pattern: src/responded_ids.txt

    - name: Auto init
      shell: pwsh
      run: |
        $repo_url = "https://api.github.com/repos/${{ github.repository }}/actions/workflows/init.yml/dispatches"
        curl -X POST `
        -H "Accept: application/vnd.github.v3+json" `
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" `
        $repo_url `
        -d '{"ref":"${{ github.ref_name}}"}'